Add ability to use glob patterns for source configs
vimc/dettl pull request #9
Opened 2019-04-04 17:02 UTC by r-ash

This PR will
* Support sourcing files using pattern matching

2019-04-08 08:17 UTC, richfitz requested changes

2019-04-08 08:17 UTC, richfitz commented on R/dettl_config.R
> +      message(sprintf("No files found matching file pattern %s", source))
I feel that this should be an error - if not then you could just use:
```r
expand_wildcards <- function(sources, path) {
  Sys.glob(file.path(sources, path))
}
```

2019-04-08 08:17 UTC, richfitz commented on R/dettl_config.R
> +  all_files <- c()
This pattern (growing a vector) is not very R-ish: more typical would be

```r
expand1 <- function(x) {
  files <- Sys.glob(x)
  if (length(files) == 0) {
    message(sprintf("No files found matching file pattern %s", x))
  }
  files
}

expand_wildcards <- function(sources, path) {
  unlist(lapply(sources, expand1, path), FALSE, FALSE)
}
```

2019-04-08 08:17 UTC, richfitz commented on R/dettl_config.R
> +    files <- Sys.glob(file.path(path, source))
If you want to separate out the path part from the pattern matching, the other option is to use `withr::with_dir` to change working directory before processing the patterns - this usually results in cleaner code

2019-04-09 11:52 UTC, r-ash commented
Thanks for the feedback above. I've addressed each of those points.

2019-04-09 16:39 UTC, richfitz approved these changes

2019-04-09 16:39 UTC, merged